apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  selector:
    matchLabels:
      app: prediction
  replicas: 3
  template:
    metadata:
      labels:
        app: prediction
    spec:
     containers:
     - name: prediction
       image: firaslam/breast-cancer-detection:1.0  
       ports:
       - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8080
  type: LoadBalancer  



      
  
  
    